services:
  votacao:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SERVICE_URL_VOTACAO_80
      - 'DB_NAME=${MYSQL_DATABASE:-votacao}'
      - 'DB_USER=${SERVICE_USER_MYSQL}'
      - 'DB_PASSWORD=${SERVICE_PASSWORD_MYSQL}'
      - MYSQL_HOST=database
      - DB_TIMEZONE=${TIMEZONE:-America/Sao_Paulo}
      - JWT_SECRET=${SERVICE_PASSWORD_64_APPLICATION}
      - EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-3600000}
      - APP_CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:?}
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://127.0.0.1:8080' ]
      interval: 5s
      timeout: 20s
      retries: 10

  nginx-proxy:
    image: nginx:1.29-alpine
    restart: unless-stopped
    depends_on:
      votacao:
        condition: service_healthy
    volumes:
      - ./dockerfiles/nginx.conf:/etc/nginx/nginx.conf:ro

    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      - 'MYSQL_ROOT_PASSWORD=${SERVICE_PASSWORD_ROOT-MYSQL}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE:-votacao}'
      - 'MYSQL_USER=${SERVICE_USER_MYSQL}'
      - 'MYSQL_PASSWORD=${SERVICE_PASSWORD_MYSQL}'
      - 'TIMEZONE=${TIMEZONE:-America/Sao_Paulo}'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: