CREATE TABLE roles
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_GESTOR');
INSERT INTO roles (name) VALUES ('ROLE_AUDITOR');
INSERT INTO roles (name) VALUES ('ROLE_VOTANTE');